src/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import main, book_page, thanks

app_name = "main_page"

urlpatterns = [
    path('', main, name='main'),
    path('book/<int:idx>/', book_page, name='book'),
    path('thanks/', thanks, name='thanks'),
]

src/vovaProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/main/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    title = models.CharField(max_length=50, verbose_name="Название книги")
    description = models.TextField(verbose_name="Описание книги")
    left = models.PositiveIntegerField(verbose_name="Книг на складе")
    image = models.ImageField(verbose_name="Обложка книги")

    def get_abolute_url(self):
        return reverse("main_page:book", kwargs={'idx': self.pk})

src/order/models.py
from django.db import models
from main.models import Book


class Customer(models.Model):
    name = models.CharField(max_length=150, verbose_name="Имя заказчика")
    email = models.EmailField(max_length=150, verbose_name="Почта заказчика")
    phone = models.IntegerField(verbose_name="Номер телефона заказчика")
    book = models.ForeignKey(Book, verbose_name="Книга", on_delete=models.CASCADE)

src/order/forms.py
from django import forms
from .models import Customer


class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ["name", "email", "phone"]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control"
                }
            ),
            "phone": forms.NumberInput(
                attrs={
                    "class": "form-control"
                }
            )
        }

    def save(self, book):
        book.left -= 1
        book.save()
        customer = Customer(
            name=self.cleaned_data["name"],
            email=self.cleaned_data["email"],
            phone=self.cleaned_data["phone"],
            book=book
        ).save()
        return customer

src/main/views.py
from django.shortcuts import render
from .models import Book
from django.shortcuts import get_object_or_404, redirect
from order.forms import CustomerForm


def main(request):
    books = Book.objects.all()
    context = {
        "books": books
    }
    return render(request, "main/main_view.html", context)


def book_page(request, idx):
    book = get_object_or_404(Book, pk=idx)
    form = CustomerForm()
    context = {
        "book": book,
        "form": form
    }
    if request.POST:
        form = CustomerForm(request.POST)
        if form.is_valid():
            form.save(book=book)
            return redirect("main_page:thanks")
    return render(request, "main/book_page_view.html", context)


def thanks(request):
    return render(request, "main/thanks_view.html")

src/order/views.py
from django.shortcuts import render

# Create your views here.

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        Book App
    {% endblock %}</title>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url "main_page:main" %}">Book app</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<main>
    {% block content %}
    {% endblock %}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
</body>
</html>

src/templates/main/book_page_view.html
{% extends "base.html" %}

{% block title %}

{% endblock %}

{% block content %}
    {% if book.left %}
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Make an order</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="{{ book.get_abolute_url }}" id="form" method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_name" class="col-form-label">Your name:</label>
                                {{ form.name }}
                            </div>
                            <div class="mb-3">
                                <label for="id_email" class="col-form-label">Your email:</label>
                                {{ form.email }}
                            </div>
                            <div class="mb-3">
                                <label for="id_phone" class="col-form-label">Your phone:</label>
                                {{ form.phone }}
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" id="submit" class="btn btn-primary">Send message</button>
                    </div>
                    <script>
                        document.querySelector("#submit").onclick = () => {
                            document.querySelector("#form").submit()
                        }
                    </script>
                </div>
            </div>
        </div>
    {% endif %}
    <section>
        <div class="container mt-3">
            <div class="row">
                <div class="col-md-4">
                    <div class="book-image">
                        <img src="{{ book.image.url }}"
                             alt="{{ book.title }}">
                    </div>
                </div>
                <div class="col-md-8">
                    <h1>{{ book.title }}</h1>
                    <p>{{ book.description }}</p>
                    {% if book.left %}
                        <p>Left: {{ book.left }}</p>
                        <a href="#" data-bs-toggle="modal" data-bs-target="#exampleModal" class="btn btn-success">Make
                            an
                            order</a>
                    {% else %}
                        Товар закончился
                    {% endif %}

                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/templates/main/main_view.html
{% extends "base.html" %}

{% block title %}
    Book | Main
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row">
                {% for book in books %}
                <div class="col-md-3 mt-3">
                    <a href="{{ book.get_abolute_url }}" class="card">
                        <img src="{{ book.image.url }}"
                             class="card-img-top" alt="image">
                        <div class="card-body">
                            <p class="card-text">{{ book.description|truncatechars:50 }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}


            </div>
        </div>
    </section>
{% endblock %}

src/templates/main/thanks_view.html
{% extends "base.html" %}

{% block title %}
    Спасибо за заказ
{% endblock %}

{% block content %}
    <section>
        <div class="container mt-3">
            <div class="row">
                <div class="d-flex justify-content-center align-items-center flex-column" style="height: 50vh">
                    <h1>Спасибо за заказ</h1>
                    <p>Тут могла быть логика оплаты или корзины, но мне лень</p>
                    <a href="{% url "main_page:main" %}" class="btn btn-success">Вернуться в магазин</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}